posts/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.all, name='all'),
    url(r'^(?P<slug>[\w-]+)/$', views.specific, name='specific'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # url(r'^$', 'simpleblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^posts/', include('posts.urls', namespace='posts')),
)

comments/models.py
from django.db import models
from posts.models import Post


class Comment(models.Model):
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True, blank=True)
#    post = models.ForeignKey('posts.Post')
    post = models.ForeignKey(Post)

posts/models.py
from django.db import models


class Post(models.Model):
    STATUS_CHOICES = (
        ('p', 'published'),
        ('u', 'unpublished')
    )
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True, blank=True)
    status = models.CharField(
        max_length=1, choices=STATUS_CHOICES, default='u')

comments/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render
from .models import Post


def all(request):
    posts = Post.objects.all().order_by('date')
    return render(
        request,
        'posts/all.html',
        {'posts': posts}
    )


def specific(request, slug):
    post = Post.objects.filter(slug=slug).first()
    print "estoy en specific"
    return render(
        request,
        'posts/specific.html',
        {'post': post}
    )

templates/posts/all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All posts</title>
</head>
<body>
<h1>My weird blog</h1>
<hr>
{% for post in posts %}
<h3><a href="{% url 'posts:specific' post.slug %}">{{ post.title }}</a></h3>
<p>
    {{ post.body }}
</p>
<div>{{ post.date }}</div>
</body>
{% empty %}
<p>Sorry, but we don't have any post still</p>
{% endfor %}
</html>

templates/posts/specific.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <p>
        {% trans "Posted at" %}: {{ post.date }}
    </p>
    <div>
       {{ post.body }}
    </div>

    <hr>
    <h2>
        Comments ({{ comments|length }})
    </h2>
    <div>
        {% for comment in comments %}
        {% empty %}
            <p>No comments in this post.</p>
            <p>Soyez le premier.</p>
        {% endfor %}
    </div>

</body>
</html>